version: "3.1"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src
    command: "uvicorn --host=0.0.0.0 main:app --reload"

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:3000"
    # volumes:
    #   - ./frontend:/usr/src/app
    command: "npm run start"
